<form  method="POST" class="needs-validation main" novalidate>
    <nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
        <div class="navbar-multiline mr-auto">
            <span class="navbar-brand" href="#0">Youtube Stream Editor</span>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                    <li class="breadcrumb-item"><a href="#0">Stream</a></li>
                    <li class="breadcrumb-item"><a href="#0">Youtube</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><?= $subtitle ?></li>
                </ol>
            </nav>
        </div>
        <button class="btn btn-primary">Save</button>
    </nav>

    <div class="container p-3">
        <div class="row mb-3">
            <?= $form->csrfField('noob') ?>
            <div class="col-md-9">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <?php if($saved): ?>
                                    <div class="alert alert-success">
                                        <strong>Success!</strong> The content successfully updated.
                                    </div>
                                <?php endif; ?>
                                <?= $form->field('title'); ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <?= $form->field('content'); ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-7">
                                <?= $form->field('embed'); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <?= $this->partial('site-meta/meta'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>